---
stages:
  - test

default:
  tags:
    - shared-small
  before_script:
    - apk add curl
    - pip install -U pip
    - pip install ansible
    - ansible-galaxy collection install .
    - cd ~/.ansible/collections/ansible_collections/proton/rackndr
    # Work around as provided https://github.com/ansible/ansible/issues/77304#issuecomment-1079442737
    - mkdir -p ~/.ansible/test/cache
    - curl --output ~/.ansible/test/cache/get_pip_23_1_2.py https://ci-files.testing.ansible.com/ansible-test/get-pip-23.1.2.py
    - pip3 config set global.proxy http://${INTERNAL_PROXY}

python3.10:
  image: ${CONTAINER_HOST}/docker.io/library/python:3.10.13-alpine3.18
  stage: test
  script:
    - ansible-test sanity --local --python 3.10

python3.11:
  image: ${CONTAINER_HOST}/docker.io/library/python:3.11.8-alpine3.18
  stage: test
  script:
    - ansible-test sanity --local --python 3.11

python3.12:
  image: ${CONTAINER_HOST}/docker.io/library/python:3.12.2-alpine3.18
  stage: test
  script:
    - ansible-test sanity --local --python 3.12
